# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-23 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name_plural': 'Issues'},
        ),
    ]
