# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20190223_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
