# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_auto_20190224_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='posted_by',
            field=models.CharField(max_length=50),
        ),
    ]
