# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-24 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_auto_20190224_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAdminPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'not scheduled'), (1, 'scheduled'), (2, 'in progress'), (3, 'completed')], default=0)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('in_current_voting_cycle', models.BooleanField(default=True)),
                ('was_successful', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='is_feature',
            field=models.BooleanField(choices=[(True, 'Feature'), (False, 'Bug Fix')], default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='issueadminpage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuetracker.Issue'),
        ),
    ]
