# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_auto_20190224_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='posted_by',
            field=models.CharField(max_length=50),
        ),
    ]
