# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0007_auto_20190224_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='issuetracker.Issue'),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
