# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20190223_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='coins_to_buy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
