# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_coins_to_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='coins_to_buy',
            field=models.IntegerField(default=0),
        ),
    ]
