# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190225_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_coins_to_buy',
            field=models.IntegerField(default=0),
        ),
    ]
