# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coins',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
